"""init

Revision ID: 0c7671ad3bd1
Revises:
Create Date: 2023-01-12 01:52:10.195566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0c7671ad3bd1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sports_grounds",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("object_name", sa.Text(), nullable=False),
        sa.Column("adm_area", sa.Text(), nullable=False),
        sa.Column("district", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("latitude", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column("longitude", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column("email", sa.Text()),
        sa.Column("phone", sa.Text()),
        sa.Column("website", sa.Text()),
        sa.Column("has_equipment_rental", sa.Boolean(), nullable=False),
        sa.Column("has_tech_service", sa.Boolean(), nullable=False),
        sa.Column("has_dressing_room", sa.Boolean(), nullable=False),
        sa.Column("has_eatery", sa.Boolean(), nullable=False),
        sa.Column("has_toilet", sa.Boolean(), nullable=False),
        sa.Column("has_wifi", sa.Boolean(), nullable=False),
        sa.Column("has_cash_machine", sa.Boolean(), nullable=False),
        sa.Column("has_first_aid_post", sa.Boolean(), nullable=False),
        sa.Column("has_music", sa.Boolean(), nullable=False),
        sa.Column("lighting", sa.Text(), nullable=False),
        sa.Column("seats", sa.BIGINT(), nullable=False),
        sa.Column("paid", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="unique_email"),
    )
    op.create_table(
        "liked_groups",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("ground_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ground_id"], ["sports_grounds.id"], name="fk_ground_id"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_user_id"),
        sa.PrimaryKeyConstraint("user_id", "ground_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("liked_groups")
    op.drop_table("users")
    op.drop_table("sports_grounds")
    # ### end Alembic commands ###
